from typing import List, Tuple, Optional
import numpy as np

class IndexBackend:
    def build(self, embeddings: np.ndarray, ids: Optional[np.ndarray] = None) -> None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    def search(self, query: np.ndarray, k: int) -> Tuple[List[int], List[float]]: ...
    def set_param(self, **kwargs) -> None: ...
    def stats(self) -> dict: ...
