from .endpoints import (
    ai,
    analytics,
    auth,
    embeddings,
    llm_assistant,
    performance_monitor,
    plan_items,
    questions,
    quiz_sessions,
    recommendations,
    scheduler,
    solutions,
    streams,
    study_plans,
    subjects,
    system_health,
    topics,
    users,
    # Async endpoints
    async_questions,
)

__all__ = [
    "auth",
    "analytics",
    "ai",
    "embeddings",
    "llm_assistant",
    "performance_monitor",
    "plan_items",
    "questions",
    "quiz_sessions",
    "recommendations",
    "scheduler",
    "solutions",
    "streams",
    "study_plans",
    "subjects",
    "system_health",
    "topics",
    "users",
    # Async endpoints
    "async_questions",
]
