"""Initial database schema

Revision ID: 485280bb3355
Revises: 
Create Date: 2025-08-17 03:43:00.277859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485280bb3355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'ENGLISH', name='subject'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'OPEN_ENDED', 'FILL_BLANK', 'TRUE_FALSE', name='questiontype'), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('original_difficulty', sa.Integer(), nullable=False),
    sa.Column('topic_category', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.Enum('PDF', 'GENERATED', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('pdf_source_path', sa.String(length=500), nullable=True),
    sa.Column('question_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_topic_category'), 'questions', ['topic_category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('current_math_level', sa.Integer(), nullable=False),
    sa.Column('current_english_level', sa.Integer(), nullable=False),
    sa.Column('learning_style', sa.Enum('VISUAL', 'AUDITORY', 'KINESTHETIC', 'MIXED', name='learningstyle'), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('error_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'ENGLISH', name='subject'), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_occurrence', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('topic_category', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_patterns_error_type'), 'error_patterns', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_patterns_subject'), 'error_patterns', ['subject'], unique=False)
    op.create_index(op.f('ix_error_patterns_topic_category'), 'error_patterns', ['topic_category'], unique=False)
    op.create_index(op.f('ix_error_patterns_user_id'), 'error_patterns', ['user_id'], unique=False)
    op.create_table('pdf_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'ENGLISH', name='subject'), nullable=False),
    sa.Column('questions_extracted', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('virus_scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'FAILED', name='virusscanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_uploads_subject'), 'pdf_uploads', ['subject'], unique=False)
    op.create_index(op.f('ix_pdf_uploads_uploaded_by'), 'pdf_uploads', ['uploaded_by'], unique=False)
    op.create_table('spaced_repetition',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_index(op.f('ix_spaced_repetition_next_review_at'), 'spaced_repetition', ['next_review_at'], unique=False)
    op.create_table('student_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('attempt_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('grammar_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attempts_attempt_date'), 'student_attempts', ['attempt_date'], unique=False)
    op.create_index(op.f('ix_student_attempts_question_id'), 'student_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_attempts_user_id'), 'student_attempts', ['user_id'], unique=False)
    op.create_table('math_error_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('math_concept', sa.String(length=100), nullable=True),
    sa.Column('error_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['student_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_error_details_attempt_id'), 'math_error_details', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_math_error_details_attempt_id'), table_name='math_error_details')
    op.drop_table('math_error_details')
    op.drop_index(op.f('ix_student_attempts_user_id'), table_name='student_attempts')
    op.drop_index(op.f('ix_student_attempts_question_id'), table_name='student_attempts')
    op.drop_index(op.f('ix_student_attempts_attempt_date'), table_name='student_attempts')
    op.drop_table('student_attempts')
    op.drop_index(op.f('ix_spaced_repetition_next_review_at'), table_name='spaced_repetition')
    op.drop_table('spaced_repetition')
    op.drop_index(op.f('ix_pdf_uploads_uploaded_by'), table_name='pdf_uploads')
    op.drop_index(op.f('ix_pdf_uploads_subject'), table_name='pdf_uploads')
    op.drop_table('pdf_uploads')
    op.drop_index(op.f('ix_error_patterns_user_id'), table_name='error_patterns')
    op.drop_index(op.f('ix_error_patterns_topic_category'), table_name='error_patterns')
    op.drop_index(op.f('ix_error_patterns_subject'), table_name='error_patterns')
    op.drop_index(op.f('ix_error_patterns_error_type'), table_name='error_patterns')
    op.drop_table('error_patterns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_topic_category'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###