"""
Type stubs for SQLAlchemy to help IDE recognition.
"""

from typing import Any, Optional, Union, List, Dict, TypeVar, Generic

# Basic SQLAlchemy imports
def select(*args: Any) -> Any: ...
def and_(*args: Any) -> Any: ...
def or_(*args: Any) -> Any: ...
def func() -> Any: ...
def text(text: str) -> Any: ...

# AsyncSession
class AsyncSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def execute(self, statement: Any) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...

# ConnectionPool
class ConnectionPool:
    @classmethod
    def from_url(cls, url: str, **kwargs: Any) -> 'ConnectionPool': ...
    async def disconnect(self) -> None: ...

# Redis
class Redis:
    def __init__(self, connection_pool: Any = None, **kwargs: Any) -> None: ...
    async def ping(self) -> bool: ...
    async def close(self) -> None: ...

# Exceptions
class SQLAlchemyError(Exception): ...
class IntegrityError(SQLAlchemyError): ...
class DisconnectionError(SQLAlchemyError): ...

class RedisError(Exception): ...
