apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rec-model-shadow
spec:
  hosts:
  - rec-model-predictor-default.your-domain
  http:
  - route:
    - destination:
        host: rec-model-predictor-default.your-domain
        subset: primary
      weight: 100
    mirror:
      host: rec-model-canary-predictor-default.your-domain
    mirrorPercentage:
      value: 10

