"""Update question model with new fields

Revision ID: 0002
Revises: 0001
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to questions table
    op.add_column('questions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('difficulty_level', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('bert_sim', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('embedding', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Copy data from old columns to new columns
    op.execute("""
        UPDATE questions 
        SET content = text,
            difficulty_level = CASE 
                WHEN difficulty = 'kolay' THEN 1
                WHEN difficulty = 'orta' THEN 3
                WHEN difficulty = 'zor' THEN 5
                ELSE 3
            END,
            question_type = 'multiple_choice',
            is_active = true,
            created_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE content IS NULL
    """)
    
    # Make new columns not nullable
    op.alter_column('questions', 'content', nullable=False)
    op.alter_column('questions', 'difficulty_level', nullable=False)
    op.alter_column('questions', 'question_type', nullable=False)
    op.alter_column('questions', 'is_active', nullable=False)
    op.alter_column('questions', 'created_at', nullable=False)
    op.alter_column('questions', 'updated_at', nullable=False)
    
    # Add foreign key constraints
    op.create_foreign_key(None, 'questions', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'])
    
    # Add indexes
    op.create_index(op.f('ix_questions_content'), 'questions', ['content'], unique=False)
    op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questions_created_by'), 'questions', ['created_by'], unique=False)
    
    # Add pgvector extension if not exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # Add embedding column with vector type
    op.execute("ALTER TABLE questions ADD COLUMN IF NOT EXISTS embedding_vector vector(384)")
    
    # Create embedding index
    op.execute("""
        CREATE INDEX IF NOT EXISTS questions_embedding_idx 
        ON questions 
        USING ivfflat (embedding_vector vector_cosine_ops)
        WITH (lists = 100)
    """)
    
    # Add missing columns to other tables
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE subjects SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('subjects', 'created_at', nullable=False)
    op.alter_column('subjects', 'updated_at', nullable=False)
    
    op.add_column('topics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE topics SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('topics', 'created_at', nullable=False)
    op.alter_column('topics', 'updated_at', nullable=False)
    
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE skills SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('skills', 'created_at', nullable=False)
    op.alter_column('skills', 'updated_at', nullable=False)
    
    # Update student_profiles with new columns
    op.add_column('student_profiles', sa.Column('total_questions_answered', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('total_correct_answers', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('average_response_time', sa.Float(), nullable=True))
    op.execute("""
        UPDATE student_profiles 
        SET total_questions_answered = 0,
            total_correct_answers = 0,
            average_response_time = 0.0
        WHERE total_questions_answered IS NULL
    """)
    op.alter_column('student_profiles', 'total_questions_answered', nullable=False)
    op.alter_column('student_profiles', 'total_correct_answers', nullable=False)
    op.alter_column('student_profiles', 'average_response_time', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove indexes
    op.drop_index(op.f('ix_questions_created_by'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
    op.drop_index(op.f('ix_questions_content'), table_name='questions')
    
    # Remove foreign key constraints
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    
    # Remove columns from questions table
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'embedding')
    op.drop_column('questions', 'bert_sim')
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'created_by')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'subject_id')
    op.drop_column('questions', 'difficulty_level')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'content')
    
    # Remove columns from other tables
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'created_at')
    op.drop_column('topics', 'updated_at')
    op.drop_column('topics', 'created_at')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    
    # Remove columns from student_profiles
    op.drop_column('student_profiles', 'average_response_time')
    op.drop_column('student_profiles', 'total_correct_answers')
    op.drop_column('student_profiles', 'total_questions_answered')
    
    # ### end Alembic commands ### 