"""Update user model and add progress endpoint support

Revision ID: 61ddf7d47693
Revises: 0002
Create Date: 2025-08-02 18:51:20.200721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ddf7d47693'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('target_success', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_id'), 'study_plans', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_id'), 'plan_items', ['id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=False)
    op.drop_index('ix_learning_sessions_id', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('ix_recommendation_logs_id', table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.add_column('question_skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('bert_sim', sa.JSON(), nullable=True))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('questions_embedding_idx', table_name='questions', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_foreign_key(None, 'questions', 'topics', ['topic_id'], ['id'])
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('student_profiles', sa.Column('total_questions_answered', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('total_correct_answers', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('average_response_time', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('student_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_student_profiles_student_id'), 'student_profiles', ['student_id'], unique=False)
    op.add_column('student_responses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('student_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.alter_column('subjects', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('subjects', 'updated_at')
    op.alter_column('student_responses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('student_responses', 'updated_at')
    op.drop_index(op.f('ix_student_profiles_student_id'), table_name='student_profiles')
    op.drop_column('student_profiles', 'updated_at')
    op.drop_column('student_profiles', 'created_at')
    op.drop_column('student_profiles', 'average_response_time')
    op.drop_column('student_profiles', 'total_correct_answers')
    op.drop_column('student_profiles', 'total_questions_answered')
    op.alter_column('skills', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('skills', 'updated_at')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_index('questions_embedding_idx', 'questions', ['embedding_vector'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('questions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('questions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('questions', 'bert_sim')
    op.drop_column('question_skills', 'created_at')
    op.create_table('recommendation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommendation_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recommendation_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recommendation_reason', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('was_selected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='recommendation_logs_question_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='recommendation_logs_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recommendation_logs_pkey')
    )
    op.create_index('ix_recommendation_logs_id', 'recommendation_logs', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='learning_sessions_student_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='learning_sessions_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='learning_sessions_pkey')
    )
    op.create_index('ix_learning_sessions_id', 'learning_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_plan_items_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_study_plans_id'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
