version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: learnai
      POSTGRES_USER: learnai
      POSTGRES_PASSWORD: learnai
    ports: ["55432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["16379:6379"]

  # qdrant (opsiyonel)
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports: ["6333:6333","6334:6334"]
  #   volumes:
  #     - qdrant_storage:/qdrant/storage

volumes:
  pg_data:
  # qdrant_storage:
