FROM pytorch/torchserve:0.11.0-cpu

USER root
RUN mkdir -p /home/model-server/model-store /home/model-server/logs /home/model-server/config
COPY serving/model-store /home/model-server/model-store

EXPOSE 8080 8081
CMD ["torchserve", "--start", "--model-store", "/home/model-server/model-store", "--ts-config", "/home/model-server/config/config.properties", "--models", "rec.mar"]


