from . import (
    ai,
    analytics,
    auth,
    embeddings,
    llm_assistant,
    performance_monitor,
    plan_items,
    questions,
    quiz_sessions,
    recommendations,
    scheduler,
    solutions,
    streams,
    study_plans,
    subjects,
    system_health,
    topics,
    users,
    # New modular routers
    ai_services,
    vector_services,
    recommendation_services,
    health,
    admin,
    gamification,
    docs,
    # Async endpoints
    async_questions,
    # New endpoints
    search,
    evaluation,
)

__all__ = [
    "auth",
    "analytics",
    "ai",
    "embeddings",
    "llm_assistant",
    "performance_monitor",
    "plan_items",
    "questions",
    "quiz_sessions",
    "recommendations",
    "scheduler",
    "solutions",
    "streams",
    "study_plans",
    "subjects",
    "system_health",
    "topics",
    "users",
    # New modular routers
    "ai_services",
    "vector_services",
    "recommendation_services",
    "health",
    "admin",
    "gamification",
    "docs",
    # Async endpoints
    "async_questions",
    # New endpoints
    "search",
    "evaluation",
]
